language: scala
sudo: false
scala:
  - 2.10.4
  - 2.11.5
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: "sbt -sbt-version 0.13.7 ++$TRAVIS_SCALA_VERSION clean coverage test coveralls scalastyle"
